runtime: custom
env: flex
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 64
liveness_check:
  path: "/_gcp/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
readiness_check:
  path: "/_gcp/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 900
